ALTER TABLE companies
  ADD COLUMN director_name VARCHAR(255) DEFAULT NULL,
  ADD COLUMN director_position VARCHAR(255) DEFAULT NULL,
  ADD COLUMN iik VARCHAR(34) DEFAULT NULL,
  ADD COLUMN bank_name VARCHAR(255) DEFAULT NULL,
  ADD COLUMN bik VARCHAR(20) DEFAULT NULL,
  ADD COLUMN kbe VARCHAR(10) DEFAULT NULL,
  ADD COLUMN legal_address VARCHAR(500) DEFAULT NULL;