spring.application.name=metrology-catalog

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/service_catalog
spring.datasource.username=root
spring.datasource.password=!59Drag0n
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=312baed003a2d0
spring.mail.password=59532f4460f98b
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

jwt.secret=metrology-catalog-secret-key-2026-very-long-string
jwt.expiration=86400000

logging.level.root=INFO
logging.level.com.catalog=DEBUG
